jenkinsci/matrix-auth-plugin

- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
Better exception message if a permission does not exist.
The current message does not indicate which permission is unknown:
```
Caused by: java.lang.IllegalArgumentException
at hudson.security.GlobalMatrixAuthorizationStrategy.add(GlobalMatrixAuthorizationStrategy.java:94)
at hudson.security.GlobalMatrixAuthorizationStrategy$DescriptorImpl.newInstance(GlobalMatrixAuthorizationStrategy.java:276)
at hudson.security.GlobalMatrixAuthorizationStrategy$DescriptorImpl.newInstance(GlobalMatrixAuthorizationStrategy.java:248)
```
New message
```
Caused by: java.lang.IllegalArgumentException: Unknown permission:"com.cloudbees.plugins.updatecenter.UpdateCenter.Configure" set to "true" for sid "configure_jenkins"
at hudson.security.GlobalMatrixAuthorizationStrategy$DescriptorImpl.newInstance(GlobalMatr …
```
> Silently ignore unknown permissions instead of throwing an IllegalArgumentException

- pom.xml
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
It's a follow-up to #2 
If "useProjectSecurity" appears in the marshalled stream before "blocksInheritance", the second option may be ignored => the project may start taking inherited permissions. However, seems the code just iterates through fields => we should not use the else clause. The assigned "prop" variable is never used, so it's another clue of the bug
@reviewbybees @stephenc
> [FIXED JENKINS-29527] - AuthorizationMatrixProperty converter: Inheritance blocking may be passed incorrectly

- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
https://issues.jenkins-ci.org/browse/JENKINS-31860
@reviewbybees 
I am not entirely happy with this approach as when we have one of the parent / child ACLs being non `SidACL` then the semantics of `Boolean hasPermission(Sid p, Permission permission)` may be subverted... IOW we have no way to differentiate between the Child ACL saying "`Boolean.FALSE`->no and don't check the parent" and the Child ACL saying "`null`->only if parent is ok"
> [JENKINS-31860] Restore return type to match API

- pom.xml
- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
- src/main/resources/index.jelly
- src/test/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixPropertyTest.java
Counterpart to https://github.com/jenkinsci/cloudbees-folder-plugin/pull/33, and would have to be released simultaneously to minimize the chance of loss of functionality. (I do not know of a way to _force_ users who upgrade `cloudbees-folder` to also upgrade `matrix-auth`, alas.)
@reviewbybees esp. @stephenc
> Add cloudbees-folder dependency

- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
Because https://github.com/jenkinsci/matrix-auth-plugin/blob/master/pom.xml#L35
Untested.
> Make extension for Folders plugin optional

- pom.xml
Bumping parent pom version fixes PCT against 2.x baselines.
@reviewbybees
> Fixes PCT against 2.x baselines.

- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
- src/main/resources/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty/config.jelly
- src/main/resources/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty/help-blocksInheritance.html
- src/test/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixPropertyTest.java
This adds the same tick-box to disable inheritance of global permissions
to Folders as already exists for Projects. Consistency!
Support for the Folder plugin seems to originally have been done by
copy-pasting in an only slightly modified version of an ancient copy of
the AuthorizationMatrixProperty.java file. This commit is as such very
similar to the patch Kohsuke once applied to the Project's AMP:
6411fffb41e4e7b217d0e841462ef23a8e62c45a
Now, these two files are close to identical, and should be refactored
into one class in my opinion:
src/main/java/hudson/security/AuthorizationMatrixProperty.java
src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
> [JENKINS-29815] Add disabling of permission inheritance for Folders

- pom.xml
- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/test/java/hudson/security/ProjectMatrixAuthorizationStrategyTest.java
This is a pretty crude approach to attempt to prevent the problem, but I'm not sure with the current form there can be a better one.
This addresses part of [JENKINS-9774](https://issues.jenkins-ci.org/browse/JENKINS-9774) by preventing accidentally empty global permissions overall (but not the parse problem -- that's handled by https://github.com/jenkinsci/matrix-auth-plugin/pull/25), and part of [JENKINS-10871](https://issues.jenkins-ci.org/browse/JENKINS-10871) by ensuring there's an admin that can log in (or, in the worst case, anonymous).
While the UX of [JENKINS-28668](https://issues.jenkins-ci.org/browse/JENKINS-28668) remains terrible, this change will prevent such accidental lockouts as well.
The current approach will result in anonymous users being granted admin permissions in …
> [JENKINS-46832] Prevent initial misconfiguration by making sure there's an admin

- src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
- src/test/java/hudson/security/ProjectMatrixAuthorizationStrategyTest.java
- src/test/resources/hudson/security/ProjectMatrixAuthorizationStrategyTest/loadEmptyAuthorizationStrategy/config.xml
- src/test/resources/hudson/security/ProjectMatrixAuthorizationStrategyTest/loadFilledAuthorizationStrategy/config.xml
I doubt anyone still cares a lot about reading configurations written before https://github.com/jenkinsci/jenkins/commit/27f8c5a67622f27d580c2c7c4cc53d7dec77fd01
OTOH, [JENKINS-9774](https://issues.jenkins-ci.org/browse/JENKINS-9774) should be resolved (sort of). Nobody has permissions, but at least it won't break Jenkins complete.
Complements https://github.com/jenkinsci/matrix-auth-plugin/pull/24
> [JENKINS-9774] Drop support for pre-2009 serialized format that resulted in errors

- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
For users that have a "full name" different from their user ID, this will show the full name, with the user ID available as tool tip.
@jenkinsci/code-reviewers mostly to get opinions on usefulness / possible unintended side effects
> [FIX JENKINS-14563] Show full name of user instead of user name

- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/test/java/org/jenkinsci/plugins/matrixauth/PermissionAdderTest.java
[JENKINS-20520](https://issues.jenkins-ci.org/browse/JENKINS-20520)
@jglick
> [FIX JENKINS-20520] Save Jenkins after adding global user permission

- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/DangerousMatrixPermissionsAdministrativeMonitor.java
- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AbstractMatrixPropertyConverter.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixPropertyDescriptor.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationProperty.java
- src/main/resources/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty/config.jelly
- src/main/resources/hudson/security/AuthorizationMatrixProperty/config.jelly
- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- src/main/resources/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty/config.jelly
- src/test/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixPropertyTest.java
- src/test/java/hudson/security/ProjectMatrixAuthorizationStrategyTest.java
- src/test/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodePropertyTest.java
- src/test/java/org/jenkinsci/plugins/matrixauth/PermissionAdderTest.java
- Drop 1.301 permission backward compatibility code (it's been more than 8 years…)
- Remove deprecated Jenkins#getActiveInstance calls
- Proper implementation of getGroups() in project-based matrix
> Various improvements towards 2.0

- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.properties
Permissions:
Actions:
Both use the user ID rather than the validated label, but that seems like a *lot* of work for relatively little benefit.
> [JENKINS-26824] Add tooltips for actions and checkboxes

- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- Always show 'authenticated' row to make it discoverable
- Use group icons and friendly localizable labels for both
- Show them on top so additions are to the bottom
- Prevent duplicate rows showing up for both
----
[JENKINS-30495](https://issues.jenkins-ci.org/browse/JENKINS-30495)
> [JENKINS-30495] Improve 'authenticated' and 'anonymous' rows

- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/DangerousMatrixPermissionsAdministrativeMonitor.java
- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AbstractAuthorizationContainerConverter.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AbstractAuthorizationPropertyConverter.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainer.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainerDescriptor.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationPropertyDescriptor.java
- src/main/java/org/jenkinsci/plugins/matrixauth/ValidationUtil.java
- src/main/resources/org/jenkinsci/plugins/matrixauth/inheritance/InheritGlobalStrategy/config.jelly
Extract an interface with default method implementations common to the strategy and the properties (as opposed to the existing one that only did code common to properties), an interface for their descriptors, and a new abstract converter.
Untested.
> Further cleanup addressing more copied code

- pom.xml
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainer.java
- src/main/java/org/jenkinsci/plugins/matrixauth/inheritance/InheritGlobalStrategy.java
- src/main/java/org/jenkinsci/plugins/matrixauth/inheritance/InheritParentStrategy.java
- src/main/java/org/jenkinsci/plugins/matrixauth/inheritance/InheritanceStrategyDescriptor.java
- src/main/java/org/jenkinsci/plugins/matrixauth/inheritance/NonInheritingStrategy.java
- src/test/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixPropertyTest.java
- src/test/java/hudson/security/AuthorizationMatrixPropertyTest.java
Supersedes https://github.com/jenkinsci/matrix-auth-plugin/pull/14
[JENKINS-34616](https://issues.jenkins-ci.org/browse/JENKINS-34616)
- ~~I don't like the fully qualified permission IDs – ideally, they would be shortened to "Class.Field" if unambiguous.~~ (JENKINS-17200)
- ~~Needs usage docs~~ Optional, sort of, snippet gen works after all.
----
Snippet generator:
> ![screen shot](https://user-images.githubusercontent.com/1831569/30508169-c06d05ea-9a90-11e7-8d6b-518726adaddb.png)
Result (formatted for readability):
```groovy
properties([
authorizationMatrix(
inheritanceStrategy: nonInheriting(), 
permissions: [
'hudson.model.Item.Read:authenticated', 
'hudson.model.Run.Delete:danielbeck', 
'hudson.model.Item.Build:danielbeck', 
'hudson.model.Item.Configure:danielbeck']
), …
```
> [JENKINS-34616] Add symbols, getter, and constructor for pipeline

- .gitignore
I expect this to take care of these lines in the release build output:
[WARNING] Ignoring unrecognized line: ?? pom.xml.releaseBackup
[WARNING] Ignoring unrecognized line: ?? release.properties
> Add ignores for maven-release-plugin

- src/test/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodePropertyTest.java
[JENKINS-47555](https://issues.jenkins-ci.org/browse/JENKINS-47555) by @andresrc 
CC @jglick Perhaps `CommandLauncher` isn't a great default for `JenkinsRule` anymore?
> [JENKINS-47555] Fix test on 2.73.2+

- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
This extension was added in 2.0, but I forgot to mark it `optional = true`.
> Don't show a warning when cloudbees-folder is missing

- src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
According the Jenkins Core docs in case of SYSTEM user we should assume
that it can do whatever he wants.
p.s. The original problem comes from `getPlugin` method that is already fixed in Core ( https://github.com/jenkinsci/jenkins/pull/3109)
> Do not perform any checks for System user

- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- src/main/resources/hudson/security/table.css
Chrome cannot apply `writing-mode` to `td`, so wrap label in `span` and rotate that.
Before:
> ![screen shot](https://user-images.githubusercontent.com/1831569/41879262-2ad9aa56-78d9-11e8-9993-a995139f54bf.png)
After:
> ![screen shot](https://user-images.githubusercontent.com/1831569/41879266-30aed06e-78d9-11e8-95f3-bfad37ac863e.png)
> [JENKINS-52167] Rotate permission table header rows in Chrome

- .mvn/extensions.xml
- .mvn/maven.config
- pom.xml
- src/main/java/hudson/security/DangerousMatrixPermissionsAdministrativeMonitor.java
Although the plugin has an explicit dependency on the `<classifier>tests</classifier>` version of `workflow-cps`, the regular test-scope dependency is pulled in transitively through `workflow-multibranch`. 
This works fine for now since the 2 current versions seem to be compatible, but in the PCT, there can be failures because `SnippitizerTester` (which comes from the `<classifier>tests</classifier>` version of `workflow-cps`) from `workflow-cps` 2.56+ is not compatible with regular `workflow-cps` 2.55-, and the PCT isn't smart enough to update the non-classifier version unless it is specified explicitly here (it updates the `workflow-multibranch` version, but that is not enough).
I also incrementalified the plugin while I was here and fixed the access-modifier issue.
> Add dependency on non-tests classifier version of workflow-cps and incrementalify

- Jenkinsfile
- pom.xml
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainer.java
For Java 11 readiness, apply recommended configuration:
https://wiki.jenkins.io/display/JENKINS/Java+11+Developer+Guidelines#Java11DeveloperGuidelines-MakesureyourpluginistestedinContinuousIntegrationonJava8andJava11atthesametime
And fixing what was revealed through this.
@jenkinsci/java11-support
> Java 11 readiness

- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/AuthorizationMatrixNodePropertyConfigurator.java
An exception will occur during startup in 2.4 when Configuration-as-Code is not installed.
> Properly work with optional dependency

- pom.xml
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainerDescriptor.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
* [JENKINS-54568](https://issues.jenkins-ci.org/browse/JENKINS-54568): Make `authorizationMatrix` work in declarative snippet generator
* [JENKINS-46914](https://issues.jenkins-ci.org/browse/JENKINS-46914): Better indicate implied permissions in the checkbox grid by disabling implied permission checkboxes
* [JENKINS-47885](https://issues.jenkins-ci.org/browse/JENKINS-47885): Make node property work in Kubernetes (and old versions of Docker) plugin templates
> [JENKINS-46914] [JENKINS-47885] [JENKINS-54568] JavaScript improvements

- pom.xml
Will get rid of the implied dependency on https://plugins.jenkins.io/jaxb
Per http://stats.jenkins.io/pluginversions/matrix-auth.html users are on that release already anyway.
> Increase core dependency to 2.164.1

- .mvn/maven.config
- README.md
- pom.xml
2.190.x is the baseline that comes without implied dependencies at the moment: https://github.com/jenkinsci/jenkins/blob/master/core/src/main/resources/jenkins/split-plugins.txt
Jenkins BOM is needed for an slf4j upper bounds problem with the new core.
> Update core dependency to 2.190.1

- pom.xml
Only affects local development with `-Djenkins.version` and similar for now, but still. `workflow-cps:2.30` still uses the removed `Memoizer`.
> Update parent POM, workflow-cps dependency for 2.223+ compatibility

- src/main/resources/hudson/security/table.css
This should help a little, but I think the main problem is in core…
> [JENKINS-36625] Allow wrap of user/group names

- CHANGELOG.md
- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainer.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- src/test/java/org/jenkinsci/plugins/matrixauth/ReadOnlyTest.java
…gurations
----
[JENKINS-62202](https://issues.jenkins-ci.org/browse/JENKINS-62202)
Regression because of https://github.com/jenkinsci/matrix-auth-plugin/pull/78
Enable permissions involved like this:
```
Item.EXTENDED_READ.enabled = true
Jenkins.SYSTEM_READ.enabled = true
Computer.EXTENDED_READ.enabled = true
```
`mvn hpi:run -Djenkins.version=2.235` helps some, but Computer/Configure can only be confirmed with https://github.com/jenkinsci/jenkins/pull/4531.
Manual testing setup:
1. `docker run --rm -ti -p 8080:8080 -e ID=4531 jenkins/core-pr-tester`
2. In Setup Wizard, install _only_ Folders Plugin
3. Create admin user
4. In Plugin Manager » Advanced, upload PR build
5. Create Manage Users, create user/user
6. In Script Console, run the script above
Now permissions can be assigned at …
> [JENKINS-62202] Fix accidental read-only mode in jobs and folders

- src/main/resources/hudson/security/AuthorizationMatrixProperty/config.groovy
[JENKINS-64661](https://issues.jenkins.io/browse/JENKINS-64661)
While the corresponding `NodeProperty` was updated to handle `null` `it`/`my` as that is part of the regular UI flow (#38), that was not done for this implementation as it's fairly unusual: It seems only the global (outside any context) snippet generator of `workflow-cps` calls this in that way, and additionally has no robustness when a particular implementation cannot handle that.
> [JENKINS-64661] Do not break global snippet generator

- src/test/java/org/jenkinsci/plugins/matrixauth/PermissionAdderTest.java
In https://github.com/jenkinsci/bom/pull/359 the test from #23 fails when `jth.jenkins-war.path` is set to the megawar. Seems that `SignupPage.submit` quietly returns even when the signup in fact fails. Trying the page interactively showed that it would refuse to proceed unless you entered an email address. Making this change makes the test pass when `jth.jenkins-war.path` is set. The test utility predates the new signup page GUI but it is not clear that is relevant; I have not figured out what about the megawar (bundled JavaScript?) would change behavior here.
> Making PermissionAdderTest run in PCT

- src/test/java/org/jenkinsci/plugins/matrixauth/ReadOnlyTest.java
Turns out 2.238 has been released 😄
> Fix read-only test that requires 2.238+

- src/test/java/org/jenkinsci/plugins/matrixauth/PermissionAdderTest.java
We seem to be generally preferring `JenkinsSessionRule` to `RestartableJenkinsRule`. The main benefit to `JenkinsSessionRule` is that `#then` runs immediately, so it plays nicely with things like `@After.`
> Migrate from RestartableJenkinsRule to JenkinsSessionRule

- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- src/main/resources/hudson/security/table.js
See https://issues.jenkins.io/browse/JENKINS-66170
This is a regression from #102 in which we moved to adjuncts, but since #82, JS was only available in read-write, and so the later change removed CSS from read-only.
@timja Could you PTAL if you have some time?
> [JENKINS-66170] Apply table style when read-only

- CHANGELOG.md
Looks like I forgot to add content for 2.6.6 and 2.6.7, probably because 2.6.6 was a security update.
> Note 2.6.6, 2.6.7, and 2.6.8 in changelog file

- src/main/resources/org/jenkinsci/plugins/matrixauth/inheritance/InheritParentStrategy/config.properties
Alternative to #105: Addresses the specific problem identified in [JENKINS-67210](https://issues.jenkins.io/browse/JENKINS-67210), while keeping compatibility with non-empty context paths.
CC @Kevin-CB
> [JENKINS-67210] Fix broken link to global security configuration

- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- src/main/resources/hudson/security/table.css
See [JENKINS-67311](https://issues.jenkins.io/browse/JENKINS-67311).
Some of the alignments are off in the old core baseline, and the margin has no effect, but I don't think I care enough to fix either. It works well enough, and the help text has problems anyway.
@timja FYI just in case, a tables to divs issue I think as this broke in 2.264.
<details>
<summary>2.222.x</summary>
> <img width="1694" alt="old-global" src="https://user-images.githubusercontent.com/1831569/144931787-85aa80bd-4d8f-4a65-9fa3-afd1e11d99c9.png">
> <img width="1567" alt="old-job" src="https://user-images.githubusercontent.com/1831569/144931792-ddfedd17-3b73-4f0c-9496-5b7e369e7d13.png">
> <img width="2018" alt="old-agent" src="https://user-images.githubusercontent.com/1831569/144931799-5412a3f5-e3a9-4837-b178-9d62b37 …
> [JENKINS-67311] Fix help button for table

- src/main/resources/hudson/security/table.js
Previously, removal of all ambiguous rows without (automatically migrated) replacement did not remove the warning block below the table. With this change, it is removed.
> Update ambiguity warning after removal of a row

- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
The current release no longer has a tooltip for the "Migrate entry to group" action from the `title` attribute, because it was automatically upgraded to symbols in recent Jenkins releases. This switches all tooltips of these actions to `tooltip` so they work again:
Fun fact: This change also demonstrates [SECURITY-2776](https://www.jenkins.io/security/advisory/2022-06-22/#SECURITY-2781) and probably should not be run on affected versions of Jenkins.
> Switch to tooltips, because title doesn't work for symbols

- src/main/resources/hudson/security/table.js
Fix [JENKINS-68922](https://issues.jenkins.io/browse/JENKINS-68922)
This still has a weakness in that we do not handle the "inactive" tooltip attribute, resulting in a DOM like
```
<a html-tooltip="Remove all permissions from __SID__" tooltip="Remove all permissions from theNewU" href="#" class="unselectall" title="Remove all permissions from theNewU"><img src="/jenkins/plugin/matrix-auth/images/unselect-all.svg" alt="Unselect all" width="16" height="16"></a>
```
This seems tolerable.
> [JENKINS-68922] Fix JS handling of 'Add user'/'Add group' buttons

- pom.xml
Job DSL no longer has a dependency on `groovy-all`.
> Upgrade Job DSL to 1.82

- CHANGELOG.md
- src/main/java/org/jenkinsci/plugins/matrixauth/ValidationUtil.java
- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.properties
- src/main/resources/org/jenkinsci/plugins/matrixauth/AmbiguityMonitor/index.properties
[JENKINS-67368](https://issues.jenkins.io/browse/JENKINS-67368)
> [JENKINS-67368] Refer to user ID instead of name where appropriate

- pom.xml
Required for https://github.com/jenkinsci/jenkins/pull/7781 / https://github.com/jenkinsci/bom/pull/1968
Could I get a release please?
The parent pom bump includes https://github.com/jenkinsci/jenkins-test-harness/pull/567 which is released in https://github.com/jenkinsci/plugin-pom/releases/tag/plugin-4.58
> Bump parent pom

- src/main/resources/hudson/security/table.js
Based on https://github.com/jenkinsci/matrix-auth-plugin/pull/139, actual changes are from 4th commit onward.
Compatibility with [JENKINS-70906](https://issues.jenkins.io/browse/JENKINS-70906).
Tested with and without https://github.com/jenkinsci/jenkins/pull/7986, including ambiguity-related code and SystemRead / ExtendedRead.
> [JENKINS-70906] Compatibility with Prototype removal

- src/main/resources/org/jenkinsci/plugins/matrixauth/AmbiguityMonitor/index.jelly
Probably caused by a core change to the styles between 2.361.4 and 2.387.3, noticed while working with #147.
> <img width="558" alt="Screenshot 2023-07-17 at 10 38 07" src="https://github.com/jenkinsci/matrix-auth-plugin/assets/1831569/cddb53da-179c-4d8d-b16a-21d6891e056c">
> <img width="557" alt="Screenshot 2023-07-17 at 10 37 53" src="https://github.com/jenkinsci/matrix-auth-plugin/assets/1831569/04c0f3f1-20f0-41bc-b358-080c0b5b1b3e">
> Wrap `<l:task/>` in `<l:tasks/>`

- src/test/java/org/jenkinsci/plugins/matrixauth/Security2180Test.java
From a PCT run:
```
java.io.IOException: …/matrix-auth-plugin/target/tmp/j h5449561387972401643/jobs/folder0/jobs/item1/builds/permalinks
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:144)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.delete(TemporaryDirectoryAllocator.java:131)
at org.jvnet.hudson.test.TemporaryDirectoryAllocator.dispose(TemporaryDire …
```
> Flakes in `Security2180Test`

- .mvn/extensions.xml
- Jenkinsfile
- pom.xml
Merely consuming dependency updates shipping support for Java 21 at compile time.
This PR doesn't need to be released.
As a side effect, increase the configuration-as-code dependency from 1647 to 1670.
> Add support for Java 21 at compile time

- src/test/java/hudson/security/ProjectMatrixAuthorizationStrategyTest.java
Jenkins version must be at least 2.387.3 as defined in the pom.  No need for the test to check if the Jenkins version is older than 2.342, since it must be at least 2.387.3.
Automated tests pass with Java 11 on Linux
> Remove outdated Jenkins version test conditional

- src/main/java/org/jenkinsci/plugins/matrixauth/AmbiguityMonitor.java
Simplifies logic introduced in #110. @Vlatombe noticed a test failure from https://github.com/jenkinsci/jenkins/pull/8979 since the logic was assuming that a save of an agent would use `Nodes` as the subject, which is now more naturally the `Node`, but anyway there was already a listener method for this.
> Simplified `NodeContributor.record` on updated

- src/test/java/org/jenkinsci/plugins/matrixauth/ReadOnlyTest.java
This plugin no longer uses the YUI buttons, so mentioning them in a comment is misleading.
(The goal is just to clean up the search results for `makeButton` in the `jenkinsci` org)
> Remove outdated comments

- pom.xml
- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
- src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.properties
- src/main/resources/hudson/security/table.js
replaces the browser built-in prompt and alert calls with the dialogs for better theming.
Manual testing
> use new dialog to prompt for user/group

- LICENSE.md
- src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/DefinitionEntry.java
- src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/GlobalMatrixAuthorizationStrategyConfigurator.java
- src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/MatrixAuthorizationStrategyConfigurator.java
- src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/PermissionDefinition.java
- src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/ProjectMatrixAuthorizationStrategyConfigurator.java
[JENKINS-75034](https://issues.jenkins.io/browse/JENKINS-75034)
Individual file license headers copyright based on Git history for each file. I confirmed with @ndeloof about his copyright.
IANAL so no idea whether the LICENSE.md without a list of contributors makes sense, but the number of copyright holders for all of this plugin is far too great to list, especially given its history as having been part of Jenkins core.
> [JENKINS-75034] Add top-level license file, backfill license headers

- Jenkinsfile
- pom.xml
- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationPropertyDescriptor.java
`mvn clean verify` both here and in `azure-ad-plugin` (with these changes)
> Migrate from EE 8 to EE 9

- .git-blame-ignore-revs
- src/main/resources/hudson/security/table.js
Run `npx prettier --print-width 999 -w jenkinsci/matrix-auth-plugin/src/main/resources/hudson/security/table.js` on this file to make it easier to read.
If we want to drop the `--print-width` option (which results in even more invasive changes) I can do that as well.
If this PR isn't desired, that is fine as well. We can simply close it and leave the status quo; I don't feel strongly about this.
None, but I trust Prettier to not introduce new bugs.
> Format file with Prettier

- src/main/resources/hudson/security/table.js
[JENKINS-75329](https://issues.jenkins.io/browse/JENKINS-75329)
`findAncestor` is marked deprecated in Jenkins core and logs a warning. As this method is used quite a lot this leads to many warnings being logged which seems to slow down the page significantly when many users/groups are present
On a page with 42 users/groups I get over 8200 calls to `findAncestor`
Interactive testing showed no more warnings in the browser console
> [JENKINS-75329] replace findAncestor with plain javascript

- src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/AuthorizationMatrixProperty.java
- src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AmbiguityMonitor.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainer.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainerDescriptor.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
- src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationProperty.java
This is needed for compatibility with core tests updated by https://github.com/jenkinsci/jenkins/pull/10426
> Makes `AuthorizationContainer` extend `Describable`
