pom.xml
src/main/java/hudson/security/AuthorizationMatrixProperty.java
src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java

Enable FindBugs for the plugin

---

src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java

https://issues.jenkins-ci.org/browse/JENKINS-46190
Originally introduced in https://github.com/jenkinsci/matrix-auth-plugin/pull/9 (1.7, June 2017)
@jenkinsci/code-reviewers

[FIX JENKINS-46190] Fix NPE since case insensitive matching

---

src/main/java/hudson/security/GlobalMatrixAuthorizationStrategy.java
src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
src/main/resources/org/jenkinsci/plugins/matrixauth/Messages.properties

@rtyler 
Skipping Overall/Administer, since that is just annoying to see everywhere.

[FIX JENKINS-32506] Add impliedBy info to tooltip

---

src/main/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty.java
src/main/java/hudson/security/AuthorizationMatrixProperty.java
src/main/java/hudson/security/ProjectMatrixAuthorizationStrategy.java
src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty.java
src/test/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixPropertyTest.java
src/test/java/hudson/security/ProjectMatrixAuthorizationStrategyTest.java
src/test/java/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodePropertyTest.java

[FIX JENKINS-5277] Ensure that creators have read and configure access

---

src/main/resources/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty/config.groovy

[JENKINS-47412](https://issues.jenkins-ci.org/browse/JENKINS-47412)

[FIX JENKINS-47412] Handle 'new node' form with null 'my' instance

---

src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainerDescriptor.java
src/test/java/org/jenkinsci/plugins/matrixauth/Jenkins57313Test.java

Supersedes https://github.com/jenkinsci/matrix-auth-plugin/pull/63

[JENKINS-57313] Fix potential NPE during form validation

---

src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.properties

Discovered a few minor issues late in the cycle and fixing those towards 2.5.

[JENKINS-46914] Fix various issues with the table UI

---

src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly

JENKINS-61205 System read support

---

.mvn/extensions.xml
pom.xml
src/test/java/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixPropertyTest.java
src/test/java/com/cloudbees/hudson/plugins/folder/properties/IdStrategyTest.java

For PCT compatibility with https://github.com/jenkinsci/jenkins/pull/4848.

[JEP-295] Avoid explicit references to AccessDeniedException in tests

---

pom.xml
src/main/resources/com/cloudbees/hudson/plugins/folder/properties/AuthorizationMatrixProperty/config.groovy
src/main/resources/hudson/security/AuthorizationMatrixProperty/config.groovy
src/main/resources/lib/matrixauth/blockWrapper.jelly
src/main/resources/org/jenkinsci/plugins/matrixauth/AuthorizationMatrixNodeProperty/config.groovy

Supersedes #83, cleaner this way.
@timja PTAL

[JENKINS-56109] Compatibility with upcoming div-based form layout

---

src/main/java/org/jenkinsci/plugins/matrixauth/AbstractAuthorizationPropertyConverter.java

Provides compatibility with https://github.com/jenkinsci/jenkins/pull/4944.
Do not rely on https://github.com/jenkinsci/xstream/commit/ff37159865ad417e075fb06d321aae7aa22ade2a.

Use ExtendedHierarchicalStreamReader

---

CHANGELOG.md

Also clean up changelog:
* Fix links to Jira
* Replace wiki links with plugin site
* Rephrase recent entries for core compatibility to indicate core versions

Add changelog entry for upcoming version 2.6.5

---

src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly

See [JENKINS-66964](https://issues.jenkins.io/browse/JENKINS-66964)
CC @Kevin-CB

[JENKINS-66964] Fix button tooltips

---

.github/workflows/jenkins-security-scan.yml

https://github.com/jenkinsci/.github/pull/75

Declare required permissions

---

src/test/java/hudson/security/ProjectMatrixAuthorizationStrategyTest.java

Make this test work on 2.342

---

pom.xml

see https://github.com/jenkinsci/bom/pull/1133#issuecomment-1165846002
(and can this be released please?)

Update parent pom to 4.41

---

Jenkinsfile
pom.xml

Update core dependency, plugin dependencies, parent POM

---

src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainer.java

[JENKINS-68581](https://issues.jenkins.io/browse/JENKINS-68581)

[JENKINS-68581] Improve Javadoc

---

src/main/resources/hudson/security/GlobalMatrixAuthorizationStrategy/config.jelly
src/main/resources/hudson/security/table.js

Adapts to https://github.com/jenkinsci/jenkins/commit/61f6553844b671a3a0dff5454464f90f3ac466c3

[JENKINS-70231] Fix tooltips on 2.379+

---

src/main/resources/org/jenkinsci/plugins/matrixauth/Messages_fr.properties

Hello !
I found a small typo error in the French translation

Fix FR typo

---

src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/MatrixAuthorizationStrategyConfigurator.java

https://github.com/jenkinsci/matrix-auth-plugin/pull/145#discussion_r1303996645
None
```[tasklist]
```

Remove MatrixAuthorizationStrategyConfigurator#getLegacyPermissions

---

src/main/java/org/jenkinsci/plugins/matrixauth/integrations/casc/PermissionDefinition.java

[JENKINS-72012](https://issues.jenkins.io/browse/JENKINS-72012)

[JENKINS-72012] Fix CasC export with non-English locales

---

src/test/java/org/jenkinsci/plugins/matrixauth/inheritance/InheritanceMigrationTest.java

Helpful in https://github.com/jenkinsci/cloudbees-folder-plugin/pull/375.

Better assertion in `InheritanceMigrationTest`

---

pom.xml
src/main/java/org/jenkinsci/plugins/matrixauth/AuthorizationContainerDescriptor.java
src/main/java/org/jenkinsci/plugins/matrixauth/ValidationUtil.java

https://groups.google.com/g/jenkinsci-dev/c/fX97wf9J--E/m/pLSAMACVAQAJ
Autotests.
Development seemed deceptive as an optional plugin dependency on CasC gave me lang3 via commons-text (before I added the plugin dependency), so needs interactive test with no optional dependencies first to be safe.
Another option would be to re-implement `StringUtils#abbreviate` and switch to `String#join`, which should take care of all current uses.

Remove commons-lang
